harnessApiVersion: '1.0'
type: PIPELINE
pipelineStages:
- type: APPROVAL
  name: Approval 0
  parallel: false
  properties:
    userGroups:
    - Account Administrator
    workflowVariables: null
    variables: null
    stageName: First STAGE
    timeoutMillis: 86400000
    approvalStateType: USER_GROUP
    sweepingOutputName: ''
  skipCondition:
    type: DO_NOT_SKIP
  stageName: First STAGE
